// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_100_platforms = "CgkIkNbx2-YEEAIQBA"; // <GPGSID>
        public const string achievement_open_the_credits = "CgkIkNbx2-YEEAIQCQ"; // <GPGSID>
        public const string achievement_i_am_a_chameleon = "CgkIkNbx2-YEEAIQBg"; // <GPGSID>
        public const string leaderboard_highscores = "CgkIkNbx2-YEEAIQAQ"; // <GPGSID>
        public const string achievement_1000_coins = "CgkIkNbx2-YEEAIQCA"; // <GPGSID>
        public const string achievement_10_platforms = "CgkIkNbx2-YEEAIQAg"; // <GPGSID>
        public const string achievement_500_coins = "CgkIkNbx2-YEEAIQBw"; // <GPGSID>
        public const string achievement_300_platfroms = "CgkIkNbx2-YEEAIQBQ"; // <GPGSID>
        public const string leaderboard_coins_gathered = "CgkIkNbx2-YEEAIQCg"; // <GPGSID>
        public const string achievement_50_platforms = "CgkIkNbx2-YEEAIQAw"; // <GPGSID>

}

